name: Push-to-EC2 instance

# Trigger deployment only on push to main branch 
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2  # Use v2 for better support

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Update and install dependencies
            sudo yum -y update
            sudo yum install -y httpd nodejs npm

            # Install PM2 for process management
            sudo npm install -g pm2

            # Navigate to application directory
            cd /home/ec2-user

            # Install Node.js dependencies
            npm install

            # Build the Node.js application (adjust this if you don't need a build step)
            sudo npm run build

            # Start the Node.js application using PM2 (adjust app.js to your entry file)
            pm2 start app.js --name "express-app"

            # Set PM2 to auto-start on reboot
            pm2 startup
            pm2 save

            # Ensure the Node.js app is running on the desired port (default: 3000)
            # You can use firewall rules if needed to allow access to this port

            # Optionally restart the httpd service if you're using Apache as a reverse proxy
            sudo systemctl restart httpd

            # Allow traffic on the application port (if needed)
            sudo firewall-cmd --zone=public --add-port=3000/tcp --permanent
            sudo firewall-cmd --reload
