name: Push-to-EC2 instance

# Trigger deployment only on push to main branch 
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2  # Update to v2 for better support

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Update and install dependencies
            sudo yum -y update
            sudo yum install -y httpd nodejs npm

            # Start and enable Apache server (if needed for static assets)
            sudo systemctl start httpd
            sudo systemctl enable httpd

            # Navigate to application directory
            cd /home/ec2-user

            # Install node dependencies
            npm install

            # Build the Node.js application (adjust this if not needed)
            sudo npm run build

            # If there are build files and you want to serve them through Apache
            cd build
            sudo mv * /var/www/html

            # If your app requires Node.js to run
            # Start the Node.js application (replace app.js with your actual entry file)
            nohup node app.js &

            # Optionally, you can use pm2 for better process management
            # sudo npm install -g pm2
            # pm2 start app.js
            # pm2 startup
            # pm2 save

            # Restart httpd service to ensure everything is properly served
            sudo systemctl restart httpd
